### ISSUE TITLE
Failure Case Study

### ISSUE THREAD

**Issue by hehaiyang111** [blanclist/ICNet#2]
闻达你好：
  论文中最后关于失败案例（显著性极差）的附录文件有公开吗？这个问题是如何解决的，注意到MSRC有很多显著性图都是无效的。

**Comment by blanclist** [comment]
> 闻达你好：
> 论文中最后关于失败案例（显著性极差）的附录文件有公开吗？这个问题是如何解决的，注意到MSRC有很多显著性图都是无效的。

您好，
        失败案例的情况在补充材料的第 4 页中有说明，链接为：
        https://papers.nips.cc/paper/2020/file/d961e9f236177d65d21100592edb0769-Supplemental.pdf
        事实上对于这个问题，我们的方法是无法处理的。尽管我们的模型允许 SISMs 是有错误的，但当大部分 SISMs 都出错、或无意义时，我们的模型也只能得到无意义的结果。不过在我论文中使用的三个测试集上，这种情况仅仅出现在 MSRC 数据集中的 “树” 类别，所以我认为这种失败情况出现的概率还是比较小的（可以从补充材料中看到模型输出的结果更像是在分割出“天空”）。
